spring.application.name=GymAdmin

# PostgreSQL Config (Render)
spring.datasource.url=jdbc:postgresql://dpg-cvlfpm6ubrc73biujf0-a.oregon-postgres.render.com:5432/admin_gym
spring.datasource.username=useradmin
spring.datasource.password=dGZUGt2PsjhdgHl4Hkcz57MqvkxcSV85
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.properties.hibernate.use_nationalized_character_data=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=false

# Puerto de backend
server.port=8082

# Logs
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Email (ya está bien configurado)
spring.mail.host=smtp.hostinger.com
spring.mail.port=587
spring.mail.username=admin_aresgym@aresgym.site
spring.mail.password=123456789.rJ
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
